name: Build Armbian with Userpatches

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [luckfox-pico-mini, luckfox-pico-max, luckfox-lyra-plus, raspberry-pi-64bit]
      fail-fast: false
    steps:
      - name: Checkout armbian/build (main) into workspace root
        uses: actions/checkout@v6
        with:
          repository: armbian/build
          ref: main

      - name: Checkout current repository into userpatches
        uses: actions/checkout@v6
        with:
          path: userpatches

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Compile ${{ matrix.config }} image
        shell: bash
        run: >
          ./compile.sh build ${{ matrix.config }}
          PREFER_DOCKER=yes
          KERNEL_CONFIGURE=no
          SHARE_LOGS=no

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.config }}
          path: output/images/*
